//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype02.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prototype02.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   【KeyChainのエラーID＆メッセージ】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K0000 {
            get {
                return ResourceManager.GetString("K0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2001:method deprecated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2001 {
            get {
                return ResourceManager.GetString("K2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2002:unknown error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2002 {
            get {
                return ResourceManager.GetString("K2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2003:file system error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2003 {
            get {
                return ResourceManager.GetString("K2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2004:feature not implemented に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2004 {
            get {
                return ResourceManager.GetString("K2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2005:persona exists already に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2005 {
            get {
                return ResourceManager.GetString("K2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2006:persona doesn’t exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2006 {
            get {
                return ResourceManager.GetString("K2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2007:keychain blockchain transaction payload too large に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2007 {
            get {
                return ResourceManager.GetString("K2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2008:insufficient free funds (of layer 1 blockchain tokens) to fund the keychain blockchain transaction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2008 {
            get {
                return ResourceManager.GetString("K2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2009:missing query result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2009 {
            get {
                return ResourceManager.GetString("K2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2010:invalid keychain key type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2010 {
            get {
                return ResourceManager.GetString("K2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2011:unconfirmed keychain tip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2011 {
            get {
                return ResourceManager.GetString("K2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2012:immature keychain tip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2012 {
            get {
                return ResourceManager.GetString("K2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2013:no confirmed keychain child trxn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2013 {
            get {
                return ResourceManager.GetString("K2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2014:on-chain keychain has been finalized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2014 {
            get {
                return ResourceManager.GetString("K2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2015:bad input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2015 {
            get {
                return ResourceManager.GetString("K2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2016:no blockchain transaction payload data found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2016 {
            get {
                return ResourceManager.GetString("K2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2017:keychain terminated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2017 {
            get {
                return ResourceManager.GetString("K2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2018:malformed op return script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2018 {
            get {
                return ResourceManager.GetString("K2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2019:error while trying to parse transaction payload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2019 {
            get {
                return ResourceManager.GetString("K2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2020:error during data marshaling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2020 {
            get {
                return ResourceManager.GetString("K2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2021:error during data unmarshaling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2021 {
            get {
                return ResourceManager.GetString("K2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2022:an exception occurred at lower library levels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2022 {
            get {
                return ResourceManager.GetString("K2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2023:query request to blockchain server failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2023 {
            get {
                return ResourceManager.GetString("K2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2024:reached the tip/leaf of the keychain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2024 {
            get {
                return ResourceManager.GetString("K2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2025:received sentinel utxo value(s) from the blockchain server so unable to calculate a balance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2025 {
            get {
                return ResourceManager.GetString("K2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2026:database has already been seeded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2026 {
            get {
                return ResourceManager.GetString("K2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2027:database file already exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2027 {
            get {
                return ResourceManager.GetString("K2027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2028:get new address failed unexpectedly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2028 {
            get {
                return ResourceManager.GetString("K2028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2029:local blockchain state is already up to date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2029 {
            get {
                return ResourceManager.GetString("K2029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2030:creation of a persona is already in progress and it is yet immature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2030 {
            get {
                return ResourceManager.GetString("K2030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2031:keychain tip certificate has expired に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2031 {
            get {
                return ResourceManager.GetString("K2031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2032:ledger transaction contains an invalid signature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2032 {
            get {
                return ResourceManager.GetString("K2032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2033:ledger transactino requires a signature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2033 {
            get {
                return ResourceManager.GetString("K2033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2034:ledger response is required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2034 {
            get {
                return ResourceManager.GetString("K2034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2035:decryption by persona is not authorized in the given encrypted data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2035 {
            get {
                return ResourceManager.GetString("K2035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2036:no recognized signer for signed data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2036 {
            get {
                return ResourceManager.GetString("K2036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2037:bad keychain tip payload public key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2037 {
            get {
                return ResourceManager.GetString("K2037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2038:no persona set as active に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2038 {
            get {
                return ResourceManager.GetString("K2038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2039:database is busy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2039 {
            get {
                return ResourceManager.GetString("K2039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2040:no keychain tip found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2040 {
            get {
                return ResourceManager.GetString("K2040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2041:license verification failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2041 {
            get {
                return ResourceManager.GetString("K2041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2042:http request returned application-level error code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2042 {
            get {
                return ResourceManager.GetString("K2042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2043:http request returned protocol-level code other than 200 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2043 {
            get {
                return ResourceManager.GetString("K2043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2044:null pointer was received for an object reference when non-null was expected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2044 {
            get {
                return ResourceManager.GetString("K2044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2045:memory allocation request failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2045 {
            get {
                return ResourceManager.GetString("K2045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2046:input file does not exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2046 {
            get {
                return ResourceManager.GetString("K2046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2047:record not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2047 {
            get {
                return ResourceManager.GetString("K2047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2048:attempted to issue an asset that was issued by another entity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2048 {
            get {
                return ResourceManager.GetString("K2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2049:authorizer’s ledger certificate signature failed verification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2049 {
            get {
                return ResourceManager.GetString("K2049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2050:ledger certificate’s target holder is not the active persona に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2050 {
            get {
                return ResourceManager.GetString("K2050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2051:ledger transaction needs a rejection signature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2051 {
            get {
                return ResourceManager.GetString("K2051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2052:contact already exists in the database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string K2052 {
            get {
                return ResourceManager.GetString("K2052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【ログメッセージ】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L0000 {
            get {
                return ResourceManager.GetString("L0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L0001 {
            get {
                return ResourceManager.GetString("L0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のメッセージダイアログが表示されました。\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L0002 {
            get {
                return ResourceManager.GetString("L0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗号化時の試験確認：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L0201 {
            get {
                return ResourceManager.GetString("L0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [いいえ]が選択されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L0201No {
            get {
                return ResourceManager.GetString("L0201No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [はい]が選択されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L0201Yes {
            get {
                return ResourceManager.GetString("L0201Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【エラーメッセージ】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0000E {
            get {
                return ResourceManager.GetString("M0000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【インフォメッセージ】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0000I {
            get {
                return ResourceManager.GetString("M0000I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【ワーニングメッセージ】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0000W {
            get {
                return ResourceManager.GetString("M0000W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションは既に起動されています。\n複数起動することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0001E {
            get {
                return ResourceManager.GetString("M0001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User IDが正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0002E {
            get {
                return ResourceManager.GetString("M0002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定中です。\nアプリケーションは閉じずにしばらくお待ちください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定が失敗しました。再度ログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0004E {
            get {
                return ResourceManager.GetString("M0004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーの設定に問題があります（Sub Nameが設定されていません）。\n管理者にご連絡ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0005E {
            get {
                return ResourceManager.GetString("M0005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初回設定：以下の内容であっていますか？\n  ・名前：{0}\n  ・Subname：{1}\n  ・Role：{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0006Q {
            get {
                return ResourceManager.GetString("M0006Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初回ログインが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0007I {
            get {
                return ResourceManager.GetString("M0007I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションのcodeが設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0008E {
            get {
                return ResourceManager.GetString("M0008E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   試験と施設が登録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0010I {
            get {
                return ResourceManager.GetString("M0010I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はすでに同名のファイルがあるためセットできません。\n（セットしたファイルはダブルクリックで削除できます） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0101E {
            get {
                return ResourceManager.GetString("M0101E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は1MBを超えています。ファイルサイズの上限は1MBまでです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0102E {
            get {
                return ResourceManager.GetString("M0102E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」の暗号化が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0201I {
            get {
                return ResourceManager.GetString("M0201I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」が暗号化できませんでした。\n{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0202E {
            get {
                return ResourceManager.GetString("M0202E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   試験名：{0}について以下のファイルを暗号化しアップロードしますがよろしいでしょうか？{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0203Q {
            get {
                return ResourceManager.GetString("M0203Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗号化がキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0204I {
            get {
                return ResourceManager.GetString("M0204I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \n※暗号化できなかったファイルが残っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0205_1 {
            get {
                return ResourceManager.GetString("M0205_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した全ファイルの処理が終了しました。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0205I {
            get {
                return ResourceManager.GetString("M0205I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗号化中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0206 {
            get {
                return ResourceManager.GetString("M0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗号化されていないファイルが残っていますがよろしいでしょうか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0207Q {
            get {
                return ResourceManager.GetString("M0207Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルリスト取得中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0301 {
            get {
                return ResourceManager.GetString("M0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルリストの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0302E {
            get {
                return ResourceManager.GetString("M0302E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   復合化がキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0303I {
            get {
                return ResourceManager.GetString("M0303I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は既に存在するため復号化できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0304E {
            get {
                return ResourceManager.GetString("M0304E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   復合化中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0305 {
            get {
                return ResourceManager.GetString("M0305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   復号合化が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0306I {
            get {
                return ResourceManager.GetString("M0306I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audit Trailsが出力されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0401I {
            get {
                return ResourceManager.GetString("M0401I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audit Trailsの出力がキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0402I {
            get {
                return ResourceManager.GetString("M0402I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象の期間にAudit Trailsがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0403I {
            get {
                return ResourceManager.GetString("M0403I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初回アクセスが確認できました。承認をおこなってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0501I {
            get {
                return ResourceManager.GetString("M0501I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初回アクセスが確認ぜきずタイムアウトしました。再度QRコードを表示してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0502I {
            get {
                return ResourceManager.GetString("M0502I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject Codeが承認されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0503I {
            get {
                return ResourceManager.GetString("M0503I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックが完了しました。QRコードを表示してスマートフォンで後続処理を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0504I {
            get {
                return ResourceManager.GetString("M0504I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名を実行します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0601Q {
            get {
                return ResourceManager.GetString("M0601Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に存在するためダウンロードできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0602E {
            get {
                return ResourceManager.GetString("M0602E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードがキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0603I {
            get {
                return ResourceManager.GetString("M0603I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0604I {
            get {
                return ResourceManager.GetString("M0604I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0605I {
            get {
                return ResourceManager.GetString("M0605I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名がキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0606I {
            get {
                return ResourceManager.GetString("M0606I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0607I {
            get {
                return ResourceManager.GetString("M0607I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0608I {
            get {
                return ResourceManager.GetString("M0608I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名依頼が保存されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0701I {
            get {
                return ResourceManager.GetString("M0701I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象データがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0801E {
            get {
                return ResourceManager.GetString("M0801E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は既に存在するため復号化できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0802E {
            get {
                return ResourceManager.GetString("M0802E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードがキャンセルされました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0803I {
            get {
                return ResourceManager.GetString("M0803I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0804 {
            get {
                return ResourceManager.GetString("M0804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0805I {
            get {
                return ResourceManager.GetString("M0805I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0901E {
            get {
                return ResourceManager.GetString("M0901E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact Listが取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M0902E {
            get {
                return ResourceManager.GetString("M0902E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスが更新されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M1001I {
            get {
                return ResourceManager.GetString("M1001I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   想定外のエラーが発生しました。\n管理者へご連絡ください。\n\n----------------------------------------\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M9000E {
            get {
                return ResourceManager.GetString("M9000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_TITLE_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_TITLE_INFO {
            get {
                return ResourceManager.GetString("MESSAGE_TITLE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_TITLE_QUESTION {
            get {
                return ResourceManager.GetString("MESSAGE_TITLE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_TITLE_WARNING {
            get {
                return ResourceManager.GetString("MESSAGE_TITLE_WARNING", resourceCulture);
            }
        }
    }
}
