export const BUSINESS_VC_REQUEST_STATUS = Object.freeze({
  INSERT: 'INSERT',
  GET_CHALLENGE_FAIL: 'GET_CHALLENGE_FAIL',
  GET_KEY_NAME_FAIL: 'GET_KEY_NAME_FAIL',
  GET_PUBLIC_KEY_FAIL: 'GET_PUBLIC_KEY_FAIL',
  CREATE_VC_FAIL: 'CREATE_VC_FAIL',
  REQUEST_VC_FAIL: 'REQUEST_VC_FAIL',
  REQUEST_VC_SUCCESS: 'REQUEST_VC_SUCCESS',
  VC_APPROVED: 'VC_APPROVED',
  VC_REJECTED: 'VC_REJECTED',
});
